Added a job to cookiecutter_self stage that checks whether the Raptor version specced in pyproject.toml is available for use as a git release tag. Also added a separate stage that takes a PR's merge commit and tags it with whatever raptor version is used at that moment.

diff --git a/devops_pipelines/templates/main.yml b/devops_pipelines/templates/main.yml
--- a/devops_pipelines/templates/main.yml
+++ b/devops_pipelines/templates/main.yml
@@ -16,6 +16,21 @@ stages:
           - checkout: self
             path: $(project_name)
           - template: /devops_pipelines/templates/pre_commit.yml
+      - job: check_version
+        displayName: 'Check if the Raptor version specified in pyproject.toml is still available'
+        steps:
+          - checkout: self
+            persistCredentials: true
+          - script: |
+              set -e
+              RELEASE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
+              echo "Checking availability of version $RELEASE_VERSION"..
+    
+              if git ls-remote --tags --exit-code origin "refs/tags/$RELEASE_VERSION" >/dev/null 2>&1; then
+                echo "ERROR: Git tag '$RELEASE_VERSION' already exists on origin."
+                exit 1
+              fi
+              echo "OK: Version $RELEASE_VERSION is available"
 
   - stage: cookiecutter_package
     jobs:
@@ -34,3 +49,23 @@ stages:
           - checkout: self
             path: $(project_name)
           - template: /devops_pipelines/templates/create_and_check_project_repo.yml
+
+  - stage: cookiecutter_tag
+    dependsOn: cookiecutter_self
+    condition: >
+      and(
+        succeeded(),
+        variables.isDev,
+        gt(variables['Build.SourceVersionParentsCount'], 1)
+      )
+    jobs:
+      - job: tag_release
+        displayName: 'Tagging the merge commit associated with the latest PR merge'
+        steps:
+          - checkout: self
+            persistCredentials: true
+          - script: |
+              set -e
+              RELEASE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
+              git tag -a "$RELEASE_VERSION" "$(variables['Build.SourceVersion'])" -m "Release $RELEASE_VERSION"
+              git push origin "$RELEASE_VERSION"
