Made release tagging conditional on Azure's default merge strategy (i.e. merge commits) and a global pipeline variable (so people can turn it off).

diff --git a/devops_pipelines/templates/main.yml b/devops_pipelines/templates/main.yml
--- a/devops_pipelines/templates/main.yml
+++ b/devops_pipelines/templates/main.yml
@@ -6,7 +6,9 @@ variables:
     value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
   - name: PublishPackage
     value: True
-
+  - name: EnforceVersioning
+    value: True
+             
 stages:
   - stage: cookiecutter_self
     jobs:
@@ -16,12 +18,14 @@ stages:
           - checkout: self
             path: $(project_name)
           - template: /devops_pipelines/templates/pre_commit.yml
+
       - job: check_version
-        displayName: 'Check if the Raptor version specified in pyproject.toml is still available'
+        condition: variables.EnforceVersioning
+        displayName: 'Check if release version specified in pyproject.toml is still available'
         steps:
           - checkout: self
             persistCredentials: true
-          - script: |
+          - bash: |
               set -e
               RELEASE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
               echo "Checking availability of version $RELEASE_VERSION"..
@@ -52,20 +56,33 @@ stages:
 
   - stage: cookiecutter_tag
     dependsOn: cookiecutter_self
-    condition: >
-      and(
-        succeeded(),
-        variables.isDev,
-        gt(variables['Build.SourceVersionParentsCount'], 1)
-      )
+    condition: and(variables.EnforceVersioning, variables.isDev)
     jobs:
-      - job: tag_release
-        displayName: 'Tagging the merge commit associated with the latest PR merge'
+      - job: detect_merge
+        displayName: 'Check if the triggering commit is a merge commit (i.e. has two parents)'
         steps:
           - checkout: self
+            fetchDepth: 0
+          - bash: |
+              set -euo pipefail
+              commit_hash="$(Build.SourceVersion)"
+              commit_parents="$(git show -s --format=%P "$commit_hash")"
+              n_parents="$(echo "$commit_parents" | wc -w | tr -d ' ')"
+              if [ "$n_parents" -lt 2 ]; then
+                echo "ERROR: We currently only support release tagging for merge commits (default Azure DevOps merge strategy)"
+                exit 1
+              fi
+
+      - job: tag_merge
+        displayName: 'Tagging the merge commit associated with the latest PR merge'
+        dependsOn: detect_merge
+        steps:  
+          - checkout: self
             persistCredentials: true
-          - script: |
-              set -e
+          - bash: |
+              set -euo pipefail
+              git config user.name  "Azure Pipelines"
+              git config user.email "ci@rotterdam.invalid"
               RELEASE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
-              git tag -a "$RELEASE_VERSION" "$(variables['Build.SourceVersion'])" -m "$(variables['Build.SourceVersionMessage'])"
+              git tag -a "$RELEASE_VERSION" "$(Build.SourceVersion)" -m "$(Build.SourceVersionMessage)"
               git push origin "$RELEASE_VERSION"
